### ISSUE TITLE
getting this error when running Evomaster  java.lang.IllegalStateException: valueSchema must not be null

### ISSUE THREAD

**Issue by magdimahmed** [EMResearch/EvoMaster#412]
Hello

I am getting this error when I try to generate tests, 
Thanks for your help
+++++++++++++++++++++++++++++++++++++++++++++++++++++++output++++++++++++++++++++++
EvoMaster version: 1.2.1
* There are 3 usable RESTful API endpoints defined in the schema configuration
10:52:24.099 [main] WARN  o.e.c.p.rest.RestActionBuilderV3 - No type/format information provided for 'GreetingMessage'. Defaulting to 'string'
* Starting to generate test cases
* Consumed search budget: 0.287%; covered targets: 0; time per test: 169.0ms (1.0 actions)
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on https://github.com/EMResearch/EvoMaster/issues
java.lang.IllegalStateException: valueSchema must not be null
        at org.evomaster.core.output.oracles.SchemaOracle$getSupportedResponse$1.accept(SchemaOracle.kt:296)
        at org.evomaster.core.output.oracles.SchemaOracle$getSupportedResponse$1.accept(SchemaOracle.kt:34)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.evomaster.core.output.oracles.SchemaOracle.getSupportedResponse(SchemaOracle.kt:266)
        at org.evomaster.core.output.oracles.SchemaOracle.generatesExpectation(SchemaOracle.kt:313)
        at org.evomaster.core.output.service.PartialOracles.activeOracles(PartialOracles.kt:174)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleAdditionalOracleTargetDescription(AbstractRestFitness.kt:220)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleResponseTargets(AbstractRestFitness.kt:209)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.restActionResultHandling(AbstractRestFitness.kt:554)
        at org.evomaster.core.problem.rest.service.RestFitness.doCalculateCoverage(RestFitness.kt:89)
        at org.evomaster.core.problem.rest.service.RestFitness.doCalculateCoverage(RestFitness.kt:17)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:59)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage$default(FitnessFunction.kt:46)
        at org.evomaster.core.search.algorithms.MioAlgorithm.search(MioAlgorithm.kt:38)
        at org.evomaster.core.Main$Companion.run(Main.kt:378)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:149)
        at org.evomaster.core.Main$Companion.main(Main.kt:73)
        at org.evomaster.core.Main.main(Main.kt)

**Comment by arcuri82** [comment]
Hi,
  can you try to run with `--expectationsActive false`, and see if you still get the same problem?

@bogdanmarculescu  is this a new bug? or something you might have already fixed since last release? if not, can you look at it?

**Comment by magdimahmed** [comment]
still same error
Thanks

 java -jar evomaster.jar --maxTime 30s --outputFolder src/test/java/io/helidonse --expectationsActive false
* 
 _____          ___  ___          _
|  ___|         |  \/  |         | |
| |____   _____ | .  . | __ _ ___| |_ ___ _ __
|  __\ \ / / _ \| |\/| |/ _` / __| __/ _ \ '__|
| |___\ V / (_) | |  | | (_| \__ \ ||  __/ |
\____/ \_/ \___/\_|  |_/\__,_|___/\__\___|_|

                    
* EvoMaster version: 1.2.1
* There are 3 usable RESTful API endpoints defined in the schema configuration
11:37:21.799 [main] WARN  o.e.c.p.rest.RestActionBuilderV3 - No type/format information provided for 'GreetingMessage'. Defaulting to 'string'
* Starting to generate test cases
* Consumed search budget: 0.202%; covered targets: 0; time per test: 118.0ms (1.0 actions)
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on https://github.com/EMResearch/EvoMaster/issues
java.lang.IllegalStateException: valueSchema must not be null
        at org.evomaster.core.output.oracles.SchemaOracle$getSupportedResponse$1.accept(SchemaOracle.kt:296)
        at org.evomaster.core.output.oracles.SchemaOracle$getSupportedResponse$1.accept(SchemaOracle.kt:34)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.evomaster.core.output.oracles.SchemaOracle.getSupportedResponse(SchemaOracle.kt:266)
        at org.evomaster.core.output.oracles.SchemaOracle.generatesExpectation(SchemaOracle.kt:313)
        at org.evomaster.core.output.service.PartialOracles.activeOracles(PartialOracles.kt:174)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleAdditionalOracleTargetDescription(AbstractRestFitness.kt:220)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleResponseTargets(AbstractRestFitness.kt:209)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.restActionResultHandling(AbstractRestFitness.kt:554)
        at org.evomaster.core.problem.rest.service.RestFitness.doCalculateCoverage(RestFitness.kt:89)
        at org.evomaster.core.problem.rest.service.RestFitness.doCalculateCoverage(RestFitness.kt:17)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:59)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage$default(FitnessFunction.kt:46)
        at org.evomaster.core.search.algorithms.MioAlgorithm.search(MioAlgorithm.kt:38)
        at org.evomaster.core.Main$Companion.run(Main.kt:378)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:149)
        at org.evomaster.core.Main$Companion.main(Main.kt:73)
        at org.evomaster.core.Main.main(Main.kt)

**Comment by arcuri82** [comment]
that is a further bug :-(  when "expectations" are off, partial oracles shouldn't had been computed

**Comment by arcuri82** [comment]
btw, is the the API you are working on open-source? or closed-source? (in the former case, it will be easier to debug this issue)

**Comment by magdimahmed** [comment]
Yeah it is close source am using Helidonframework for Microservices but nothing special, I got the driver running and open api is retiring the correct response?

**Comment by arcuri82** [comment]
is the OpenAPI automatically generated, or was it written by hand?

**Comment by magdimahmed** [comment]
for now it is static  if evoMaster works for us will created dynamically here is my openapi.yaml

openapi: 3.0.0
info:
  title: Helidon SE Quickstart Example
  description: A very simple application to reply with friendly greetings
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local test server

paths:
  /greet:
    get:
      summary: Returns a generic greeting
      description: Greets the user generically
      responses:
        default:
          description: Simple JSON containing the greeting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetingMessage'
  /greet/greeting:
    put:
      summary: Set the greeting prefix
      description: Permits the client to set the prefix part of the greeting ("Hello")
      requestBody:
        description: Conveys the new greeting prefix to use in building greetings
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GreetingMessage'
            examples:
              greeting:
                summary: Example greeting message to update
                value: New greeting message
      responses:
        "200":
          description: OK
          content:
            application/json: {}
  /greet/{name}:
    get:
      summary: Returns a personalized greeting
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: Simple JSON containing the greeting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetingMessage'
components:
  schemas:
    GreetingMessage:
      properties:
        message:
          type: string

**Comment by arcuri82** [comment]
in `/greet/greeting`, it seems that the `responses` has no `schema` definition.

**Comment by arcuri82** [comment]
cam try to update that, and see if still get the same problem (anyway we still need to fix EM to do not crash in this situations)

**Comment by magdimahmed** [comment]
still same error

responses:
        "200":
          description: OK
          content:
            application/json:
            schema:
              $ref: '#/components/schemas/GreetingMessage'

**Comment by arcuri82** [comment]
i made a quick fix in the branch `issue-412`. could you try that out? (need to build `evomaster.jar` locally, or download it from Github Actions when the build is completed)

**Comment by magdimahmed** [comment]
sure I can download it ,thanks a lot for all you help in this, will update you

**Comment by magdimahmed** [comment]
I guess the fix requires 1.2.2?
 EvoMaster version: 1.2.2-SNAPSHOT
* [ERROR] ERROR in the Remote EvoMaster Driver: There is a mismatch between the DTO that EvoMaster Driver is sending and what the EvoMaster Core process (this process) is expecting to receive. Are you sure you are using the same matching versions? This EvoMaster Core process version is: 1.2.2-SNAPSHOT
  Look at the logs of the EvoMaster Driver to help debugging this problem.
mahmedsamacsMBP:helidon-quickstart-se mahmedsa-mac$

**Comment by arcuri82** [comment]
hi,
 ah, yes. there is incompatible changes in the driver. until we make a new release (sometime this month),

you need to run:
```
git clone https://github.com/EMResearch/EvoMaster.git

mvn clean install -DskipTests
```

then, in the driver, update client library to `1.2.2-SNAPSHOT`, and run EM from `core/target/evomaster.jar`

and then please tell me if you still see the same issue

**Comment by magdimahmed** [comment]
Hi 
am still getting this error after building Evomaster

 java -jar core/target/evomaster.jar --maxTime 1m --outputFolder src/test/java/em --expectationsActive false

 EvoMaster version: 1.2.2-SNAPSHOT
* [ERROR] ERROR in the Remote EvoMaster Driver: There is a mismatch between the DTO that EvoMaster Driver is sending and what the EvoMaster Core process (this process) is expecting to receive. Are you sure you are using the same matching versions? This EvoMaster Core process version is: 1.2.2-SNAPSHOT
  Look at the logs of the EvoMaster Driver to help debugging this problem.

**Comment by arcuri82** [comment]
hi,

 in your driver, you need to update `evomaster-client-java-controller` from `1.2.1` to `1.2.2-SNAPSHOT`  to see the changes.

**Comment by magdimahmed** [comment]
Thanks a lot Andrea, it seems to work know ( I did update my pom file but forgot to re-start the driver)
Will update you once we try it in our codebase. Thank you for your prompt reply

+++++++++++++++++++++++++++++++++++++++
* EvoMaster version: 1.2.2-SNAPSHOT
* There are 3 usable RESTful API endpoints defined in the schema configuration
10:47:48.825 [main] WARN  o.e.c.p.rest.RestActionBuilderV3 - No type/format information provided for 'GreetingMessage'. Defaulting to 'string'
* Starting to generate test cases
* Consumed search budget: 99.920%; covered targets: 49; time per test: 2.2ms (1.0 actions)
* Going to save 3 tests to src/test/java/io/helidon/examples/quickstart/se
* Evaluated tests: 25733
* Evaluated actions: 25733
* Needed budget: 0%
* Passed time (seconds): 60
* Execution time per test (ms): Avg=2.16 , min=1.00 , max=152.00
* Computation overhead between tests (ms): Avg=0.17 , min=0.00 , max=75.00
* Covered targets (lines, branches, faults, etc.): 49
* Potential faults: 0
* Bytecode line coverage: 28% (22 out of 78 in 2 units/classes)
* EvoMaster process has completed successfully
* Use --help and visit http://www.evomaster.org to learn more about available options

**Comment by arcuri82** [comment]
good ;)

I will close this issue when we make a new release

**Comment by arcuri82** [comment]
this should be now fixed in the new `1.3.0` release

**Comment by magdimahmed** [comment]
Got it thanks a lot Andrea~Magdi
    On Friday, December 3, 2021, 03:50:51 AM PST, Andrea Arcuri ***@***.***> wrote:  
 
 


this should be now fixed in the new 1.3.0 release

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by magdimahmed** [comment]
Hi Andrea quick question when is it going to be available on maven
Thanks~Magdi
    On Friday, December 3, 2021, 03:50:51 AM PST, Andrea Arcuri ***@***.***> wrote:  
 
 


this should be now fixed in the new 1.3.0 release

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arcuri82** [comment]
Hi. It is already on Maven. It is just that version badges can take up to 24h to update

**Comment by magdimahmed** [comment]
Yeah sure, I still see 1.2.1 as the latest, will try again on Monday
Thanks~Magdi
    On Friday, December 3, 2021, 09:09:49 AM PST, Andrea Arcuri ***@***.***> wrote:  
 
 


Hi. It is already on Maven. It is just that version badges can take up to 24h to update

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
